SELECT `500_050_MasterSummaryStatsAndAttrbs`.season, 
                  `500_050_MasterSummaryStatsAndAttrbs`.league, 
                  `500_050_MasterSummaryStatsAndAttrbs`.team, 
                  `500_050_MasterSummaryStatsAndAttrbs`.name, 
                  `500_050_MasterSummaryStatsAndAttrbs`.Age, 
                  `500_050_MasterSummaryStatsAndAttrbs`.Nationality, 
                  `500_050_MasterSummaryStatsAndAttrbs`.Height, 
                  `500_050_MasterSummaryStatsAndAttrbs`.Position, 
                  `500_050_MasterSummaryStatsAndAttrbs`.Dribbling, 
                  `500_050_MasterSummaryStatsAndAttrbs`.SprintSpeed, 
                  `500_050_MasterSummaryStatsAndAttrbs`.Agility, 
                  `500_050_MasterSummaryStatsAndAttrbs`.Strength, 
                  `500_050_MasterSummaryStatsAndAttrbs`.playTime, 
                  `500_050_MasterSummaryStatsAndAttrbs`.shots, 
                  `500_050_MasterSummaryStatsAndAttrbs`.shotsOnTarget, 
                  `500_050_MasterSummaryStatsAndAttrbs`.goals, 
                  `500_050_MasterSummaryStatsAndAttrbs`.assists, 
                  `500_050_MasterSummaryStatsAndAttrbs`.foulsDrawn, 
                  `500_050_MasterSummaryStatsAndAttrbs`.fouls, 
                  `500_050_MasterSummaryStatsAndAttrbs`.ownGoal, 
                  `500_050_MasterSummaryStatsAndAttrbs`.saves
                  FROM 500_050_MasterSummaryStatsAndAttrbs
                  WHERE ((`500_050_MasterSummaryStatsAndAttrbs`.name) in @ply_nm_str)